
name: OneVA Pharmacy
port: 36500
acceptedSocketTimeout: 15000
threadPoolSize: 10
threadPoolMax: 25
threadKeepAlive: 8000
routings:
  - name: QBP^Q13
    responseTimeout: 75000
    messageType: QBP
    triggerEvent: Q13
    endpoint: http://localhost:8080/onevapharm/hoh/v251/query
    version: 2.5.1
  - name: RDS^O13
    responseTimeout: 75000
    messageType: RDS
    triggerEvent: O13
    endpoint: http://localhost:8080/onevapharm/hoh/v251/fill
    version: 2.5.1
