
package gov.va.med.cds.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClinicalDataServiceSynchronousInterface", targetNamespace = "http://client.cds.med.va.gov", wsdlLocation = "file:./wsdl/cds-service.wsdl")
public class ClinicalDataServiceSynchronousInterface_Service
    extends Service
{

    private final static URL CLINICALDATASERVICESYNCHRONOUSINTERFACE_WSDL_LOCATION;
    private final static WebServiceException CLINICALDATASERVICESYNCHRONOUSINTERFACE_EXCEPTION;
    private final static QName CLINICALDATASERVICESYNCHRONOUSINTERFACE_QNAME = new QName("http://client.cds.med.va.gov", "ClinicalDataServiceSynchronousInterface");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:wsdl/cds-service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLINICALDATASERVICESYNCHRONOUSINTERFACE_WSDL_LOCATION = url;
        CLINICALDATASERVICESYNCHRONOUSINTERFACE_EXCEPTION = e;
    }

    public ClinicalDataServiceSynchronousInterface_Service() {
        super(__getWsdlLocation(), CLINICALDATASERVICESYNCHRONOUSINTERFACE_QNAME);
    }

    public ClinicalDataServiceSynchronousInterface_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLINICALDATASERVICESYNCHRONOUSINTERFACE_QNAME, features);
    }

    public ClinicalDataServiceSynchronousInterface_Service(URL wsdlLocation) {
        super(wsdlLocation, CLINICALDATASERVICESYNCHRONOUSINTERFACE_QNAME);
    }

    public ClinicalDataServiceSynchronousInterface_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLINICALDATASERVICESYNCHRONOUSINTERFACE_QNAME, features);
    }

    public ClinicalDataServiceSynchronousInterface_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClinicalDataServiceSynchronousInterface_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClinicalDataServiceSynchronousInterface
     */
    @WebEndpoint(name = "ClinicalDataServiceSynchronousInterfaceHttpPort")
    public ClinicalDataServiceSynchronousInterface getClinicalDataServiceSynchronousInterfaceHttpPort() {
        return super.getPort(new QName("http://client.cds.med.va.gov", "ClinicalDataServiceSynchronousInterfaceHttpPort"), ClinicalDataServiceSynchronousInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClinicalDataServiceSynchronousInterface
     */
    @WebEndpoint(name = "ClinicalDataServiceSynchronousInterfaceHttpPort")
    public ClinicalDataServiceSynchronousInterface getClinicalDataServiceSynchronousInterfaceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://client.cds.med.va.gov", "ClinicalDataServiceSynchronousInterfaceHttpPort"), ClinicalDataServiceSynchronousInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLINICALDATASERVICESYNCHRONOUSINTERFACE_EXCEPTION!= null) {
            throw CLINICALDATASERVICESYNCHRONOUSINTERFACE_EXCEPTION;
        }
        return CLINICALDATASERVICESYNCHRONOUSINTERFACE_WSDL_LOCATION;
    }

}
