//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClinicalDataPatient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClinicalDataPatient">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestedNationalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="requestedResolvedIdentifiers" type="{Basedatatypes}HL72PersonIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="requestedExcludedIdentifiers" type="{Basedatatypes}HL72PersonIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="resultantIdentifiers" type="{Basedatatypes}HL72PersonIdentifier" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="outpatientMedicationPromises" type="{Pharmacy}OutpatientMedicationPromise"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClinicalDataPatient", namespace = "Common", propOrder = {
    "requestedNationalId",
    "requestedResolvedIdentifiers",
    "requestedExcludedIdentifiers",
    "resultantIdentifiers",
    "outpatientMedicationPromises"
})
public class ClinicalDataPatient {

    protected String requestedNationalId;
    protected List<HL72PersonIdentifier> requestedResolvedIdentifiers;
    protected List<HL72PersonIdentifier> requestedExcludedIdentifiers;
    protected List<HL72PersonIdentifier> resultantIdentifiers;
    protected List<OutpatientMedicationPromise> outpatientMedicationPromises;

    /**
     * Gets the value of the requestedNationalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestedNationalId() {
        return requestedNationalId;
    }

    /**
     * Sets the value of the requestedNationalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestedNationalId(String value) {
        this.requestedNationalId = value;
    }

    /**
     * Gets the value of the requestedResolvedIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedResolvedIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedResolvedIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HL72PersonIdentifier }
     * 
     * 
     */
    public List<HL72PersonIdentifier> getRequestedResolvedIdentifiers() {
        if (requestedResolvedIdentifiers == null) {
            requestedResolvedIdentifiers = new ArrayList<HL72PersonIdentifier>();
        }
        return this.requestedResolvedIdentifiers;
    }

    /**
     * Gets the value of the requestedExcludedIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestedExcludedIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestedExcludedIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HL72PersonIdentifier }
     * 
     * 
     */
    public List<HL72PersonIdentifier> getRequestedExcludedIdentifiers() {
        if (requestedExcludedIdentifiers == null) {
            requestedExcludedIdentifiers = new ArrayList<HL72PersonIdentifier>();
        }
        return this.requestedExcludedIdentifiers;
    }

    /**
     * Gets the value of the resultantIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resultantIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResultantIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HL72PersonIdentifier }
     * 
     * 
     */
    public List<HL72PersonIdentifier> getResultantIdentifiers() {
        if (resultantIdentifiers == null) {
            resultantIdentifiers = new ArrayList<HL72PersonIdentifier>();
        }
        return this.resultantIdentifiers;
    }

    /**
     * Gets the value of the outpatientMedicationPromises property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outpatientMedicationPromises property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutpatientMedicationPromises().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutpatientMedicationPromise }
     * 
     * 
     */
    public List<OutpatientMedicationPromise> getOutpatientMedicationPromises() {
        if (outpatientMedicationPromises == null) {
            outpatientMedicationPromises = new ArrayList<OutpatientMedicationPromise>();
        }
        return this.outpatientMedicationPromises;
    }

}
