//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MedicationDispense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedicationDispense">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dispenseDate" type="{Basedatatypes}PointInTime" minOccurs="0"/>
 *         &lt;element name="fillDate" type="{Basedatatypes}PointInTime" minOccurs="0"/>
 *         &lt;element name="quantityDispensed" type="{Basedatatypes}PhysicalQuantity" minOccurs="0"/>
 *         &lt;element name="currentProvider" type="{Common}PractitionerLite" minOccurs="0"/>
 *         &lt;element name="currentProviderComments" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="loginDate" type="{Basedatatypes}PointInTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicationDispense", namespace = "Pharmacy", propOrder = {
    "comments",
    "dispenseDate",
    "fillDate",
    "quantityDispensed",
    "currentProvider",
    "currentProviderComments",
    "loginDate"
})
@XmlSeeAlso({
    OutpatientMedicationDispense.class
})
public abstract class MedicationDispense {

    protected List<String> comments;
    protected PointInTime dispenseDate;
    protected PointInTime fillDate;
    protected PhysicalQuantity quantityDispensed;
    protected PractitionerLite currentProvider;
    protected List<String> currentProviderComments;
    protected PointInTime loginDate;

    /**
     * Gets the value of the comments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getComments() {
        if (comments == null) {
            comments = new ArrayList<String>();
        }
        return this.comments;
    }

    /**
     * Gets the value of the dispenseDate property.
     * 
     * @return
     *     possible object is
     *     {@link PointInTime }
     *     
     */
    public PointInTime getDispenseDate() {
        return dispenseDate;
    }

    /**
     * Sets the value of the dispenseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInTime }
     *     
     */
    public void setDispenseDate(PointInTime value) {
        this.dispenseDate = value;
    }

    /**
     * Gets the value of the fillDate property.
     * 
     * @return
     *     possible object is
     *     {@link PointInTime }
     *     
     */
    public PointInTime getFillDate() {
        return fillDate;
    }

    /**
     * Sets the value of the fillDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInTime }
     *     
     */
    public void setFillDate(PointInTime value) {
        this.fillDate = value;
    }

    /**
     * Gets the value of the quantityDispensed property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalQuantity }
     *     
     */
    public PhysicalQuantity getQuantityDispensed() {
        return quantityDispensed;
    }

    /**
     * Sets the value of the quantityDispensed property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalQuantity }
     *     
     */
    public void setQuantityDispensed(PhysicalQuantity value) {
        this.quantityDispensed = value;
    }

    /**
     * Gets the value of the currentProvider property.
     * 
     * @return
     *     possible object is
     *     {@link PractitionerLite }
     *     
     */
    public PractitionerLite getCurrentProvider() {
        return currentProvider;
    }

    /**
     * Sets the value of the currentProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link PractitionerLite }
     *     
     */
    public void setCurrentProvider(PractitionerLite value) {
        this.currentProvider = value;
    }

    /**
     * Gets the value of the currentProviderComments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the currentProviderComments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCurrentProviderComments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCurrentProviderComments() {
        if (currentProviderComments == null) {
            currentProviderComments = new ArrayList<String>();
        }
        return this.currentProviderComments;
    }

    /**
     * Gets the value of the loginDate property.
     * 
     * @return
     *     possible object is
     *     {@link PointInTime }
     *     
     */
    public PointInTime getLoginDate() {
        return loginDate;
    }

    /**
     * Sets the value of the loginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInTime }
     *     
     */
    public void setLoginDate(PointInTime value) {
        this.loginDate = value;
    }

}
