//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MedicationPromise complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedicationPromise">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recordIdentifier" type="{Basedatatypes}HL72EntityIdentifier"/>
 *         &lt;element name="pdtsPrescriptionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prescriptionId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pharmacyPatientType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="specialDrugTracking" type="{Pharmacy}SpecialDrugTracking" minOccurs="0"/>
 *         &lt;element name="dataEnterer" type="{Common}PractitionerParticipationLite" minOccurs="0"/>
 *         &lt;element name="pharmacyRequest" type="{Pharmacy}PharmacyRequest" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicationPromise", namespace = "Pharmacy", propOrder = {
    "recordIdentifier",
    "pdtsPrescriptionId",
    "prescriptionId",
    "pharmacyPatientType",
    "specialDrugTracking",
    "dataEnterer",
    "pharmacyRequest"
})
@XmlSeeAlso({
    OutpatientMedicationPromise.class
})
public abstract class MedicationPromise {

    @XmlElement(required = true)
    protected HL72EntityIdentifier recordIdentifier;
    protected String pdtsPrescriptionId;
    protected String prescriptionId;
    protected String pharmacyPatientType;
    protected SpecialDrugTracking specialDrugTracking;
    protected PractitionerParticipationLite dataEnterer;
    protected PharmacyRequest pharmacyRequest;

    /**
     * Gets the value of the recordIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link HL72EntityIdentifier }
     *     
     */
    public HL72EntityIdentifier getRecordIdentifier() {
        return recordIdentifier;
    }

    /**
     * Sets the value of the recordIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72EntityIdentifier }
     *     
     */
    public void setRecordIdentifier(HL72EntityIdentifier value) {
        this.recordIdentifier = value;
    }

    /**
     * Gets the value of the pdtsPrescriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdtsPrescriptionId() {
        return pdtsPrescriptionId;
    }

    /**
     * Sets the value of the pdtsPrescriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdtsPrescriptionId(String value) {
        this.pdtsPrescriptionId = value;
    }

    /**
     * Gets the value of the prescriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriptionId() {
        return prescriptionId;
    }

    /**
     * Sets the value of the prescriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriptionId(String value) {
        this.prescriptionId = value;
    }

    /**
     * Gets the value of the pharmacyPatientType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharmacyPatientType() {
        return pharmacyPatientType;
    }

    /**
     * Sets the value of the pharmacyPatientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharmacyPatientType(String value) {
        this.pharmacyPatientType = value;
    }

    /**
     * Gets the value of the specialDrugTracking property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialDrugTracking }
     *     
     */
    public SpecialDrugTracking getSpecialDrugTracking() {
        return specialDrugTracking;
    }

    /**
     * Sets the value of the specialDrugTracking property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialDrugTracking }
     *     
     */
    public void setSpecialDrugTracking(SpecialDrugTracking value) {
        this.specialDrugTracking = value;
    }

    /**
     * Gets the value of the dataEnterer property.
     * 
     * @return
     *     possible object is
     *     {@link PractitionerParticipationLite }
     *     
     */
    public PractitionerParticipationLite getDataEnterer() {
        return dataEnterer;
    }

    /**
     * Sets the value of the dataEnterer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PractitionerParticipationLite }
     *     
     */
    public void setDataEnterer(PractitionerParticipationLite value) {
        this.dataEnterer = value;
    }

    /**
     * Gets the value of the pharmacyRequest property.
     * 
     * @return
     *     possible object is
     *     {@link PharmacyRequest }
     *     
     */
    public PharmacyRequest getPharmacyRequest() {
        return pharmacyRequest;
    }

    /**
     * Sets the value of the pharmacyRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmacyRequest }
     *     
     */
    public void setPharmacyRequest(PharmacyRequest value) {
        this.pharmacyRequest = value;
    }

}
