//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MedicationInstructionComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedicationInstructionComponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="conjunction" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="dispenseUnitsPerDose" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dosageOrdered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="noun" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="route" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="schedule" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="verb" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="giveUnits" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="intendedDuration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicationInstructionComponent", namespace = "Pharmacy", propOrder = {
    "conjunction",
    "dispenseUnitsPerDose",
    "dosageOrdered",
    "noun",
    "route",
    "schedule",
    "verb",
    "giveUnits",
    "intendedDuration"
})
public class MedicationInstructionComponent {

    protected HL72CodedElementLite conjunction;
    protected String dispenseUnitsPerDose;
    protected String dosageOrdered;
    protected HL72CodedElementLite noun;
    protected HL72CodedElementLite route;
    protected HL72CodedElementLite schedule;
    protected HL72CodedElementLite verb;
    protected HL72CodedElementLite giveUnits;
    protected String intendedDuration;

    /**
     * Gets the value of the conjunction property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getConjunction() {
        return conjunction;
    }

    /**
     * Sets the value of the conjunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setConjunction(HL72CodedElementLite value) {
        this.conjunction = value;
    }

    /**
     * Gets the value of the dispenseUnitsPerDose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispenseUnitsPerDose() {
        return dispenseUnitsPerDose;
    }

    /**
     * Sets the value of the dispenseUnitsPerDose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispenseUnitsPerDose(String value) {
        this.dispenseUnitsPerDose = value;
    }

    /**
     * Gets the value of the dosageOrdered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDosageOrdered() {
        return dosageOrdered;
    }

    /**
     * Sets the value of the dosageOrdered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDosageOrdered(String value) {
        this.dosageOrdered = value;
    }

    /**
     * Gets the value of the noun property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getNoun() {
        return noun;
    }

    /**
     * Sets the value of the noun property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setNoun(HL72CodedElementLite value) {
        this.noun = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setRoute(HL72CodedElementLite value) {
        this.route = value;
    }

    /**
     * Gets the value of the schedule property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getSchedule() {
        return schedule;
    }

    /**
     * Sets the value of the schedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setSchedule(HL72CodedElementLite value) {
        this.schedule = value;
    }

    /**
     * Gets the value of the verb property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getVerb() {
        return verb;
    }

    /**
     * Sets the value of the verb property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setVerb(HL72CodedElementLite value) {
        this.verb = value;
    }

    /**
     * Gets the value of the giveUnits property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getGiveUnits() {
        return giveUnits;
    }

    /**
     * Sets the value of the giveUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setGiveUnits(HL72CodedElementLite value) {
        this.giveUnits = value;
    }

    /**
     * Gets the value of the intendedDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntendedDuration() {
        return intendedDuration;
    }

    /**
     * Sets the value of the intendedDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntendedDuration(String value) {
        this.intendedDuration = value;
    }

}
