//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.va.med.cds package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OutpatientMedicationDispenseNumberOfRefillsRemaining_QNAME = new QName("", "numberOfRefillsRemaining");
    private final static QName _OutpatientMedicationPromiseNumberOfRefillsAuthorized_QNAME = new QName("", "numberOfRefillsAuthorized");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.va.med.cds
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MedicationInstructionComponent }
     * 
     */
    public MedicationInstructionComponent createMedicationInstructionComponent() {
        return new MedicationInstructionComponent();
    }

    /**
     * Create an instance of {@link DispensedDrugInstance }
     * 
     */
    public DispensedDrugInstance createDispensedDrugInstance() {
        return new DispensedDrugInstance();
    }

    /**
     * Create an instance of {@link OutpatientMedicationDispense }
     * 
     */
    public OutpatientMedicationDispense createOutpatientMedicationDispense() {
        return new OutpatientMedicationDispense();
    }

    /**
     * Create an instance of {@link SpecialDrugTracking }
     * 
     */
    public SpecialDrugTracking createSpecialDrugTracking() {
        return new SpecialDrugTracking();
    }

    /**
     * Create an instance of {@link WbcObservation }
     * 
     */
    public WbcObservation createWbcObservation() {
        return new WbcObservation();
    }

    /**
     * Create an instance of {@link CancelAct }
     * 
     */
    public CancelAct createCancelAct() {
        return new CancelAct();
    }

    /**
     * Create an instance of {@link PharmacyRequest }
     * 
     */
    public PharmacyRequest createPharmacyRequest() {
        return new PharmacyRequest();
    }

    /**
     * Create an instance of {@link ActivityLog }
     * 
     */
    public ActivityLog createActivityLog() {
        return new ActivityLog();
    }

    /**
     * Create an instance of {@link OutpatientMedicationPromise }
     * 
     */
    public OutpatientMedicationPromise createOutpatientMedicationPromise() {
        return new OutpatientMedicationPromise();
    }

    /**
     * Create an instance of {@link HL72PersonIdentifier }
     * 
     */
    public HL72PersonIdentifier createHL72PersonIdentifier() {
        return new HL72PersonIdentifier();
    }

    /**
     * Create an instance of {@link HL72PersonName }
     * 
     */
    public HL72PersonName createHL72PersonName() {
        return new HL72PersonName();
    }

    /**
     * Create an instance of {@link HL72FacilityIdentifier }
     * 
     */
    public HL72FacilityIdentifier createHL72FacilityIdentifier() {
        return new HL72FacilityIdentifier();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link HL72OrganizationIdentifier }
     * 
     */
    public HL72OrganizationIdentifier createHL72OrganizationIdentifier() {
        return new HL72OrganizationIdentifier();
    }

    /**
     * Create an instance of {@link HL72LocationIdentifier }
     * 
     */
    public HL72LocationIdentifier createHL72LocationIdentifier() {
        return new HL72LocationIdentifier();
    }

    /**
     * Create an instance of {@link HL72CodedElementLite }
     * 
     */
    public HL72CodedElementLite createHL72CodedElementLite() {
        return new HL72CodedElementLite();
    }

    /**
     * Create an instance of {@link PointInTime }
     * 
     */
    public PointInTime createPointInTime() {
        return new PointInTime();
    }

    /**
     * Create an instance of {@link HL72EntityIdentifier }
     * 
     */
    public HL72EntityIdentifier createHL72EntityIdentifier() {
        return new HL72EntityIdentifier();
    }

    /**
     * Create an instance of {@link HL72CodedElement }
     * 
     */
    public HL72CodedElement createHL72CodedElement() {
        return new HL72CodedElement();
    }

    /**
     * Create an instance of {@link PhysicalQuantity }
     * 
     */
    public PhysicalQuantity createPhysicalQuantity() {
        return new PhysicalQuantity();
    }

    /**
     * Create an instance of {@link PharmacyDivision }
     * 
     */
    public PharmacyDivision createPharmacyDivision() {
        return new PharmacyDivision();
    }

    /**
     * Create an instance of {@link PatientLite }
     * 
     */
    public PatientLite createPatientLite() {
        return new PatientLite();
    }

    /**
     * Create an instance of {@link PractitionerLite }
     * 
     */
    public PractitionerLite createPractitionerLite() {
        return new PractitionerLite();
    }

    /**
     * Create an instance of {@link TreatmentFactor }
     * 
     */
    public TreatmentFactor createTreatmentFactor() {
        return new TreatmentFactor();
    }

    /**
     * Create an instance of {@link Medicine }
     * 
     */
    public Medicine createMedicine() {
        return new Medicine();
    }

    /**
     * Create an instance of {@link ClinicalDataPatient }
     * 
     */
    public ClinicalDataPatient createClinicalDataPatient() {
        return new ClinicalDataPatient();
    }

    /**
     * Create an instance of {@link PharmacyOrderableItem }
     * 
     */
    public PharmacyOrderableItem createPharmacyOrderableItem() {
        return new PharmacyOrderableItem();
    }

    /**
     * Create an instance of {@link PractitionerParticipationLite }
     * 
     */
    public PractitionerParticipationLite createPractitionerParticipationLite() {
        return new PractitionerParticipationLite();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfRefillsRemaining", scope = OutpatientMedicationDispense.class)
    public JAXBElement<Integer> createOutpatientMedicationDispenseNumberOfRefillsRemaining(Integer value) {
        return new JAXBElement<Integer>(_OutpatientMedicationDispenseNumberOfRefillsRemaining_QNAME, Integer.class, OutpatientMedicationDispense.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "numberOfRefillsAuthorized", scope = OutpatientMedicationPromise.class)
    public JAXBElement<Integer> createOutpatientMedicationPromiseNumberOfRefillsAuthorized(Integer value) {
        return new JAXBElement<Integer>(_OutpatientMedicationPromiseNumberOfRefillsAuthorized_QNAME, Integer.class, OutpatientMedicationPromise.class, value);
    }

}
