//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OutpatientMedicationDispense complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OutpatientMedicationDispense">
 *   &lt;complexContent>
 *     &lt;extension base="{Pharmacy}MedicationDispense">
 *       &lt;sequence>
 *         &lt;element name="daysSupply" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="identifier" type="{Basedatatypes}HL72EntityIdentifier" minOccurs="0"/>
 *         &lt;element name="levelOfUnderstanding" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="mailWindow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="releaseDate" type="{Basedatatypes}PointInTime" minOccurs="0"/>
 *         &lt;element name="wasPatientCounseled" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="division" type="{Common}PharmacyDivision" minOccurs="0"/>
 *         &lt;element name="dispensedDrug" type="{Pharmacy}DispensedDrugInstance" minOccurs="0"/>
 *         &lt;element name="pharmacist" type="{Common}PractitionerParticipationLite" minOccurs="0"/>
 *         &lt;element name="cmopEventStatus" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="numberOfRefillsRemaining" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OutpatientMedicationDispense", namespace = "Pharmacy", propOrder = {
    "daysSupply",
    "identifier",
    "levelOfUnderstanding",
    "mailWindow",
    "releaseDate",
    "wasPatientCounseled",
    "division",
    "dispensedDrug",
    "pharmacist",
    "cmopEventStatus",
    "numberOfRefillsRemaining"
})
public class OutpatientMedicationDispense
    extends MedicationDispense
{

    protected String daysSupply;
    protected HL72EntityIdentifier identifier;
    protected HL72CodedElementLite levelOfUnderstanding;
    protected String mailWindow;
    protected PointInTime releaseDate;
    protected HL72CodedElementLite wasPatientCounseled;
    protected PharmacyDivision division;
    protected DispensedDrugInstance dispensedDrug;
    protected PractitionerParticipationLite pharmacist;
    protected HL72CodedElementLite cmopEventStatus;
    @XmlElementRef(name = "numberOfRefillsRemaining", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> numberOfRefillsRemaining;

    /**
     * Gets the value of the daysSupply property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaysSupply() {
        return daysSupply;
    }

    /**
     * Sets the value of the daysSupply property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaysSupply(String value) {
        this.daysSupply = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link HL72EntityIdentifier }
     *     
     */
    public HL72EntityIdentifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72EntityIdentifier }
     *     
     */
    public void setIdentifier(HL72EntityIdentifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the levelOfUnderstanding property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getLevelOfUnderstanding() {
        return levelOfUnderstanding;
    }

    /**
     * Sets the value of the levelOfUnderstanding property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setLevelOfUnderstanding(HL72CodedElementLite value) {
        this.levelOfUnderstanding = value;
    }

    /**
     * Gets the value of the mailWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailWindow() {
        return mailWindow;
    }

    /**
     * Sets the value of the mailWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailWindow(String value) {
        this.mailWindow = value;
    }

    /**
     * Gets the value of the releaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link PointInTime }
     *     
     */
    public PointInTime getReleaseDate() {
        return releaseDate;
    }

    /**
     * Sets the value of the releaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInTime }
     *     
     */
    public void setReleaseDate(PointInTime value) {
        this.releaseDate = value;
    }

    /**
     * Gets the value of the wasPatientCounseled property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getWasPatientCounseled() {
        return wasPatientCounseled;
    }

    /**
     * Sets the value of the wasPatientCounseled property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setWasPatientCounseled(HL72CodedElementLite value) {
        this.wasPatientCounseled = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link PharmacyDivision }
     *     
     */
    public PharmacyDivision getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmacyDivision }
     *     
     */
    public void setDivision(PharmacyDivision value) {
        this.division = value;
    }

    /**
     * Gets the value of the dispensedDrug property.
     * 
     * @return
     *     possible object is
     *     {@link DispensedDrugInstance }
     *     
     */
    public DispensedDrugInstance getDispensedDrug() {
        return dispensedDrug;
    }

    /**
     * Sets the value of the dispensedDrug property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispensedDrugInstance }
     *     
     */
    public void setDispensedDrug(DispensedDrugInstance value) {
        this.dispensedDrug = value;
    }

    /**
     * Gets the value of the pharmacist property.
     * 
     * @return
     *     possible object is
     *     {@link PractitionerParticipationLite }
     *     
     */
    public PractitionerParticipationLite getPharmacist() {
        return pharmacist;
    }

    /**
     * Sets the value of the pharmacist property.
     * 
     * @param value
     *     allowed object is
     *     {@link PractitionerParticipationLite }
     *     
     */
    public void setPharmacist(PractitionerParticipationLite value) {
        this.pharmacist = value;
    }

    /**
     * Gets the value of the cmopEventStatus property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getCmopEventStatus() {
        return cmopEventStatus;
    }

    /**
     * Sets the value of the cmopEventStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setCmopEventStatus(HL72CodedElementLite value) {
        this.cmopEventStatus = value;
    }

    /**
     * Gets the value of the numberOfRefillsRemaining property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getNumberOfRefillsRemaining() {
        return numberOfRefillsRemaining;
    }

    /**
     * Sets the value of the numberOfRefillsRemaining property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setNumberOfRefillsRemaining(JAXBElement<Integer> value) {
        this.numberOfRefillsRemaining = value;
    }

}
