//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PatientLite complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PatientLite">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{Basedatatypes}HL72PersonIdentifier"/>
 *         &lt;element name="name" type="{Basedatatypes}HL72PersonName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PatientLite", namespace = "Common", propOrder = {
    "identifier",
    "name"
})
public class PatientLite {

    @XmlElement(required = true)
    protected HL72PersonIdentifier identifier;
    protected HL72PersonName name;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link HL72PersonIdentifier }
     *     
     */
    public HL72PersonIdentifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72PersonIdentifier }
     *     
     */
    public void setIdentifier(HL72PersonIdentifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link HL72PersonName }
     *     
     */
    public HL72PersonName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72PersonName }
     *     
     */
    public void setName(HL72PersonName value) {
        this.name = value;
    }

}
