//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PharmacyOrderableItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PharmacyOrderableItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemCode" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *         &lt;element name="dosageFormCode" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PharmacyOrderableItem", namespace = "Common", propOrder = {
    "itemCode",
    "dosageFormCode"
})
public class PharmacyOrderableItem {

    protected HL72CodedElementLite itemCode;
    protected HL72CodedElementLite dosageFormCode;

    /**
     * Gets the value of the itemCode property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getItemCode() {
        return itemCode;
    }

    /**
     * Sets the value of the itemCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setItemCode(HL72CodedElementLite value) {
        this.itemCode = value;
    }

    /**
     * Gets the value of the dosageFormCode property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getDosageFormCode() {
        return dosageFormCode;
    }

    /**
     * Sets the value of the dosageFormCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setDosageFormCode(HL72CodedElementLite value) {
        this.dosageFormCode = value;
    }

}
