//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 07:51:00 PM EST 
//


package gov.va.med.cds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PharmacyRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PharmacyRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cosigner" type="{Common}PractitionerParticipationLite" minOccurs="0"/>
 *         &lt;element name="orderedMedication" type="{Common}Medicine" minOccurs="0"/>
 *         &lt;element name="genericRequestIdentifier" type="{Basedatatypes}HL72EntityIdentifier" minOccurs="0"/>
 *         &lt;element name="orderLocationIdentifier" type="{Basedatatypes}HL72LocationIdentifier" minOccurs="0"/>
 *         &lt;element name="orderedItem" type="{Common}PharmacyOrderableItem" minOccurs="0"/>
 *         &lt;element name="orderingInstitutionIdentifier" type="{Basedatatypes}HL72OrganizationIdentifier" minOccurs="0"/>
 *         &lt;element name="orderDate" type="{Basedatatypes}PointInTime" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusModifier" type="{Basedatatypes}HL72CodedElementLite" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PharmacyRequest", namespace = "Pharmacy", propOrder = {
    "cosigner",
    "orderedMedication",
    "genericRequestIdentifier",
    "orderLocationIdentifier",
    "orderedItem",
    "orderingInstitutionIdentifier",
    "orderDate",
    "status",
    "statusModifier"
})
public class PharmacyRequest {

    protected PractitionerParticipationLite cosigner;
    protected Medicine orderedMedication;
    protected HL72EntityIdentifier genericRequestIdentifier;
    protected HL72LocationIdentifier orderLocationIdentifier;
    protected PharmacyOrderableItem orderedItem;
    protected HL72OrganizationIdentifier orderingInstitutionIdentifier;
    protected PointInTime orderDate;
    protected String status;
    protected HL72CodedElementLite statusModifier;

    /**
     * Gets the value of the cosigner property.
     * 
     * @return
     *     possible object is
     *     {@link PractitionerParticipationLite }
     *     
     */
    public PractitionerParticipationLite getCosigner() {
        return cosigner;
    }

    /**
     * Sets the value of the cosigner property.
     * 
     * @param value
     *     allowed object is
     *     {@link PractitionerParticipationLite }
     *     
     */
    public void setCosigner(PractitionerParticipationLite value) {
        this.cosigner = value;
    }

    /**
     * Gets the value of the orderedMedication property.
     * 
     * @return
     *     possible object is
     *     {@link Medicine }
     *     
     */
    public Medicine getOrderedMedication() {
        return orderedMedication;
    }

    /**
     * Sets the value of the orderedMedication property.
     * 
     * @param value
     *     allowed object is
     *     {@link Medicine }
     *     
     */
    public void setOrderedMedication(Medicine value) {
        this.orderedMedication = value;
    }

    /**
     * Gets the value of the genericRequestIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link HL72EntityIdentifier }
     *     
     */
    public HL72EntityIdentifier getGenericRequestIdentifier() {
        return genericRequestIdentifier;
    }

    /**
     * Sets the value of the genericRequestIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72EntityIdentifier }
     *     
     */
    public void setGenericRequestIdentifier(HL72EntityIdentifier value) {
        this.genericRequestIdentifier = value;
    }

    /**
     * Gets the value of the orderLocationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link HL72LocationIdentifier }
     *     
     */
    public HL72LocationIdentifier getOrderLocationIdentifier() {
        return orderLocationIdentifier;
    }

    /**
     * Sets the value of the orderLocationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72LocationIdentifier }
     *     
     */
    public void setOrderLocationIdentifier(HL72LocationIdentifier value) {
        this.orderLocationIdentifier = value;
    }

    /**
     * Gets the value of the orderedItem property.
     * 
     * @return
     *     possible object is
     *     {@link PharmacyOrderableItem }
     *     
     */
    public PharmacyOrderableItem getOrderedItem() {
        return orderedItem;
    }

    /**
     * Sets the value of the orderedItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmacyOrderableItem }
     *     
     */
    public void setOrderedItem(PharmacyOrderableItem value) {
        this.orderedItem = value;
    }

    /**
     * Gets the value of the orderingInstitutionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link HL72OrganizationIdentifier }
     *     
     */
    public HL72OrganizationIdentifier getOrderingInstitutionIdentifier() {
        return orderingInstitutionIdentifier;
    }

    /**
     * Sets the value of the orderingInstitutionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72OrganizationIdentifier }
     *     
     */
    public void setOrderingInstitutionIdentifier(HL72OrganizationIdentifier value) {
        this.orderingInstitutionIdentifier = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link PointInTime }
     *     
     */
    public PointInTime getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointInTime }
     *     
     */
    public void setOrderDate(PointInTime value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusModifier property.
     * 
     * @return
     *     possible object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public HL72CodedElementLite getStatusModifier() {
        return statusModifier;
    }

    /**
     * Sets the value of the statusModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HL72CodedElementLite }
     *     
     */
    public void setStatusModifier(HL72CodedElementLite value) {
        this.statusModifier = value;
    }

}
